### ISSUE TITLE
example your images

### ISSUE THREAD

**Issue by BlackMix** [querycap/istio#1]
Hi, sorry for asking, but where do I get an example of istio installation setup with your images for me test?
I tried following the istio site but their explanation is a bit confusing and I can't run some things because of failed for volume "istiod-ca-cert" etc.

some people can run but do not share how they set up or put the .yaml with examples, maybe it is simple for some but for me I am confused.
Maybe if I edit all the yaml files, but there are so many that I don't know which one has an image to edit the docker hub.

kubernetes is supposed to be something simple with helm but installing istio on arm64 is kind of complicated without a doc explaining haha lol

**Comment by BlackMix** [comment]
My bad, i got success install now, but your image jaegertracing-all-in-one have some error, I think got error at build or better push arm64 without amd64

**Comment by morlay** [comment]
@BlackMix 
jaegertracing-all-in-one you means [querycap/jaegertracing-all-in-one](https://hub.docker.com/r/querycap/jaegertracing-all-in-one/tags) ？

our case is running on multi arch cluster（arm64 & amd64）
so oci images is needed.

We deployed by istio/operator. example here.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: querycapistio
  tag: 1.6.4
  addonComponents:
    grafana:
      enabled: true
      k8s:
        replicaCount: 1
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
    tracing:
      enabled: true
  components:
    egressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-egressgateway
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        service:
          ports:
          - name: http2
            port: 80
          - name: https
            port: 443
          - name: tls
            port: 15443
            targetPort: 15443
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        service:
          ports:
          - name: status-port
            nodePort: 32758
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: http2
            nodePort: 30113
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            nodePort: 31438
            port: 443
            protocol: TCP
            targetPort: 8443
          - name: tls
            nodePort: 31127
            port: 15443
            protocol: TCP
            targetPort: 15443
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
      name: istio-ingressgateway
  values:
    kiali:
      hub: docker.io/querycap
      tag: v1.20.0
    tracing:
      jaeger:
        accessMode: ReadWriteMany
        hub: docker.io/querycap/jaegertracing-all-in-one
        memory:
          max_traces: 50000
        persist: false
        spanStorageType: badger
        storageClassName: ""
        tag: "latest"
      nodeSelector: {}
      podAntiAffinityLabelSelector: []
      podAntiAffinityTermLabelSelector: []
      provider: jaeger
      service:
        annotations: {}
        externalPort: 9411
        name: http-query
        type: ClusterIP
```
